name: Publish Package

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn workspace @fdiskas/devtalks-ui-components build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @fdiskas/devtalks-ui-components build
      - run: yarn workspace @fdiskas/devtalks-ui-components version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - run: yarn workspace @fdiskas/devtalks-ui-components publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @fdiskas/devtalks-ui-components build
      - run: yarn workspace @fdiskas/devtalks-ui-components version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - run: yarn workspace @fdiskas/devtalks-ui-components publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
